### ISSUE TITLE
Dictionaries are being initialized in reverse order.

### ISSUE THREAD

**Issue by LittleToonCat** [Pypperoni/pypperoni#5]
Initializing a dictionary like this works normally in a normal Python interpreter:
```python
dict = {'Hello': 1,
        'World!': 2}
{'Hello': 1, 'World!': 2}
```
But when ran through a Pypperoni build, it returns like this:
```python
dict = {'Hello': 1,
        'World!': 2}
{'World!': 2, 'Hello': 1}
```
While accessing values directly works fine, but it could be problematic if `dict.keys()` and `dict.values()` are used within a Pypperoni compiled application.

```python
print(list(dict.keys()))
['World!', 'Hello']
print(list(dict.values()))
[2, 1]
```
But what makes it really confusing that in my testing, when comparing the result of any of the functions to a list with the expected result, it returns `True`, as if nothing is wrong!

Attached is a zip file which contains the script that replicates the bug with comments documenting what outputs in the interpreter and Pypperoni respectively.

[dictionary-bug.zip](https://github.com/Pypperoni/pypperoni/files/4868243/dictionary-bug.zip)

**Comment by loblao** [comment]
Before Python 3.7, dictionary order is an implementation detail. Even though the behavior you expect is how CPython 3.6 implements it, Pypperoni doesn't guarantee it. Therefore, this is not a bug. You should use `collections.OrderedDict` if you need insertion ordering. 

That said, this is not intentional. Something got overlooked. It would be nice if dictionaries had the same behavior as on CPython 3.6 so a pull request fixing this is welcome.

By the way, assertions are removed when compiling. That's why it doesn't fail as expected.

**Comment by LittleToonCat** [comment]
I've been testing out `collections.OrderedDict` for a bit.  Turns out when you initialize it this way (passing a dictionary), The problem reproduces:

```python
dict = collections.OrderedDict({'Hello': 1,
                                'World!': 2})
```
Interperter:
```python
OrderedDict([('Hello', 1), ('World!', 2)])
```
Pypperoni:
```python
OrderedDict([('World!', 2), ('Hello', 1)])
````

While initializing it this way (with list of tuples) behaves normally:
```python
dict = collections.OrderedDict([('Hello', 1),
                                ('World!', 2)])

OrderedDict([('Hello', 1), ('World!', 2)])
```

So the issue points out to in the way dictionaries are being initialized.

> assertions are removed when compiling.

Oof yeah you're right.  To be fair I've written the sample code really late at night.  I replaced them with `if` cases, and the tests works properly now.

```
Keys: ['World!', 'Hello']
Expecting: ['Hello', 'World!']
Failed! Got "['World!', 'Hello']" instead.
Values: [2, 1]
Expecting: [1, 2]
Failed! Got "[2, 1]" instead.
```
